osx_image: xcode7
language: objective-c
env:
  matrix:
    - 'DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=8.4" CONFIGURATION="Release"       SCHEME="XCDYouTubeKit iOS Static Library"'
before_install:
  - xcrun simctl list
  - brew update
install:
  - brew install coreutils
  - gem install specific_install --no-rdoc --no-ri --no-document --quiet
  - gem specific_install -l https://www.github.com/0xced/xcpretty.git -b uncaught-exceptions
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - sudo easy_install cpp-coveralls
script:
  - open -b com.apple.iphonesimulator
  - ./Scripts/run-tests.sh
after_success:
  - '[ "$CONFIGURATION" == "Code Coverage" ] && coveralls --include XCDYouTubeKit'
after_failure:
  - cat xcodebuild.log && sleep 5
